TestProjects/PerceptionURP/Assets/Scenes/SampleScene.unity
com.unity.perception/Runtime/GroundTruth/GroundTruthCrossPipelinePass.cs
com.unity.perception/Runtime/GroundTruth/GroundTruthLabelSetupSystem.cs
com.unity.perception/Runtime/GroundTruth/GroundTruthPass.cs
com.unity.perception/Runtime/GroundTruth/IGroundTruthGenerator.cs
com.unity.perception/Runtime/GroundTruth/InstanceSegmentationCrossPipelinePass.cs
com.unity.perception/Runtime/GroundTruth/ObjectCountPass.cs
com.unity.perception/Runtime/GroundTruth/RenderedObjectInfoGenerator.cs
com.unity.perception/Runtime/GroundTruth/SemanticSegmentationCrossPipelinePass.cs
com.unity.perception/Tests/Runtime/GroundTruthTests/SegmentationGroundTruthTests.cs

Adding support for SkinnedMeshRenderers in ground truth generation.
Added SkinnedMeshRenderer variant of existing test.
<br>
<br>
Tested SynthDet and added tests in package. Segmentation and bounding boxes are reporting correct values.
<br>
<br>

Skinned mesh support

---

LICENSE.md
com.unity.perception/CHANGELOG.md
com.unity.perception/LICENSE.md
com.unity.perception/Runtime/GroundTruth/DatasetCapture.cs
com.unity.perception/Runtime/GroundTruth/Ego.cs
com.unity.perception/Runtime/GroundTruth/PerceptionCamera.cs
com.unity.perception/package.json

Cleanup to satisfy Package Validation Suite. Licence and changelog are tweaked and a few missing API docs have been added.
**Tests Added**: N/A
<br>
<br>
<br>
<br>

Release cleanup

---

.yamato/environments.yml
.yamato/promotion.yml
.yamato/publish.yml
.yamato/upm-ci-full.yml
.yamato/upm-ci-testprojects.yml

Changing the promotion file and publish, publish trigger on any branch.
Promotion requires the release tag for the promotion of the package from the internal server
Updated the environments file so all yml files are using it  
2019.3
**Tests Added**: NO
<br>
<br>
**Core Scenario Tested**: CI
<br>
**At Risk Areas**: Promotion and publish
<br>

(WIP) - Promotion setup and an environment file

---

TestProjects/PerceptionHDRP/Assets/csc.rsp
TestProjects/PerceptionHDRP/Assets/csc.rsp.meta
TestProjects/PerceptionURP/Assets/ExampleScripts/CustomAnnotationAndMetricReporter.cs
TestProjects/PerceptionURP/Assets/csc.rsp
TestProjects/PerceptionURP/Assets/csc.rsp.meta
com.unity.perception/CHANGELOG.md
com.unity.perception/Documentation~/DatasetCapture.md
com.unity.perception/Runtime/GroundTruth/Labelers/SemanticSegmentationLabeler.cs
com.unity.perception/Runtime/GroundTruth/PerceptionCamera.cs
com.unity.perception/Runtime/GroundTruth/SimulationState_Json.cs
com.unity.perception/Tests/Runtime/GroundTruthTests/SegmentationGroundTruthTests.cs

Copy of https://github.com/Unity-Technologies/com.unity.perception/pull/38 for 0.2.0

Fix warnings 0.2.0

---

com.unity.perception/Documentation~/Randomization/Index.md

made some changes around the explanation of domain randomization and added a reference to the paper that first used it. Other very minor changes in the text

intro to domain randomization

---

TestProjects/PerceptionURP/Assets/Scenes/SampleScene.unity
com.unity.perception/Editor/GroundTruth/LabelingEditor.cs

Aisv760 editor bugs - fixes for 759, 760, 761

---

com.unity.perception/Runtime/GroundTruth/Labeling/Labeling.cs

Quick doc update to Labeling
<br>
<br>
<br>
<br>

Clarification to changing Labeling at runtime

---

com.unity.perception/CHANGELOG.md

Retroactively adding updates to the changelog

Changelog updates

---

com.unity.perception/Documentation~/PerceptionCamera.md

Adding short limitations section to docs for PerceptionCamera
None needed

Adding Limitations section to PerceptionCamera.md

---

com.unity.perception/CHANGELOG.md

Updating changelog for 0.4.0 release

---

com.unity.perception/Editor/GroundTruth/CameraLabelerDrawer.cs
com.unity.perception/Editor/GroundTruth/PerceptionCameraEditor.cs
com.unity.perception/Editor/Randomization/Uxml/ParameterConfiguration.uxml
com.unity.perception/Editor/Randomization/Uxml/ScenarioBaseElement.uxml
com.unity.perception/Runtime/GroundTruth/Labelers/BoundingBoxLabeler.cs
com.unity.perception/Runtime/GroundTruth/Labelers/CameraLabeler.cs
com.unity.perception/Runtime/GroundTruth/Labelers/ObjectCountLabeler.cs
com.unity.perception/Runtime/GroundTruth/Labelers/RenderedObjectInfoLabeler.cs
com.unity.perception/Runtime/GroundTruth/Labelers/SemanticSegmentationLabeler.cs
com.unity.perception/Runtime/GroundTruth/Labelers/Visualization/HUDPanel.cs
com.unity.perception/Runtime/GroundTruth/Labeling/Labeling.cs
com.unity.perception/Runtime/GroundTruth/PerceptionCamera.cs

Informative tooltips and ui labels

---

com.unity.perception/Runtime/GroundTruth/SimulationState.cs
com.unity.perception/Tests/Runtime/GroundTruthTests/DatasetCaptureSensorSchedulingTests.cs

SequenceTimeOfNextCapture was reporting time with respect to two
different frames depending on context: either it would report absolute
time since the start of the sequence, if the first capture had not been
completed, or it would report the amount of time left until the next
capture, relative to the current time.
Removed logic which reported relative time, which seems like it was not
part of any code path, or was being corrected for elsewhere in
SimulationState's update loop. Removed some of the error correction in
the update loop and added stricter expectations for the management of
the timing code.
Added unit tests to ensure function reports time we'd expect regardless
of context.
Handling of the SensorData struct is pretty loosey-goosey in SimulationState, and …

Fixes math in SimulationState SequenceTimeOfNextCapture

---

README.md

Add citation to README.md

---

com.unity.perception/CHANGELOG.md
com.unity.perception/Runtime/GroundTruth/Labelers/ObjectCountLabeler.cs
com.unity.perception/Runtime/GroundTruth/Labelers/RenderedObjectInfoLabeler.cs
com.unity.perception/Runtime/GroundTruth/Labelers/Visualization/HUDPanel.cs

Aisv756 obj count bug

---

com.unity.perception/CHANGELOG.md
com.unity.perception/Documentation~/Tutorial/Phase1.md
com.unity.perception/Documentation~/Tutorial/TUTORIAL.md
com.unity.perception/Runtime/GroundTruth/PerceptionCamera.cs
com.unity.perception/package.json

This is the 0.5.0 release branch.

0.5.0 staging

---

com.unity.perception/Documentation~/Tutorial/Phase1.md
com.unity.perception/Documentation~/Tutorial/Phase3.md
com.unity.perception/Tests/Runtime/GroundTruthTests/LabelEntryMatchCacheTests.cs

**Tests Modified**: 
- Fixed improper ScriptableObject instantiation in LabelEntryMatchCacheTests

Replaced new with ScriptableObject.CreateInstance<T>()

---

com.unity.perception/Documentation~/Tutorial/Phase3.md
com.unity.perception/Documentation~/Tutorial/TUTORIAL.md
com.unity.perception/Editor/Randomization/Editors/RunInUSimWindow.cs

Usim branding fix (changed mentions of Usim in the tutorial to Unity Simulation)

---

com.unity.perception/Documentation~/Tutorial/Phase3.md

Updating language used in Unity Simulation section to more accurately reflect the taxonomy and concepts used.

Update phase3 docs

---

com.unity.perception/Documentation~/Tutorial/Phase1.md
com.unity.perception/Documentation~/Tutorial/Phase2.md
com.unity.perception/Documentation~/Tutorial/Phase3.md
com.unity.perception/Documentation~/Tutorial/TUTORIAL.md

Fixed a few typos and punctuation issues in the tutorial

---

com.unity.perception/Documentation~/SetupSteps.md
com.unity.perception/Documentation~/index.md

A few minor changes to the docs here, including fixing a couple of broken links

Fix broken links and other doc cleanup

---

com.unity.perception/Runtime/GroundTruth/InstanceIdToColorMapping.cs
com.unity.perception/Runtime/GroundTruth/Labelers/BoundingBox3DLabeler.cs

Just updated some xmldoc to pass validation

Fixed some issues with xmldoc

---

com.unity.perception/package.json

Upgraded to simulation core 0.0.10-preview.20

---

com.unity.perception/Documentation~/Randomization/Scenarios.md

Updated scenarios doc with constants configuration instructions

Updated scenarios doc with constants configuration instructions

---

com.unity.perception/package.json

Upgraded to com.simulation.capture 0.0.10-preview.14

---

com.unity.perception/CHANGELOG.md
com.unity.perception/package.json

Update version and changelog master dec2020

---

com.unity.perception/Documentation~/Tutorial/Phase1.md

Quotation marks on docker command

---

com.unity.perception/Editor/GroundTruth/LabelConfigEditor.cs

Minor fix to label config editor: Make sure serialized object is updated on scheduled model check

---

com.unity.perception/CHANGELOG.md
com.unity.perception/Runtime/Randomization/Randomizers/Randomizer.cs
com.unity.perception/Runtime/Randomization/Scenarios/ScenarioBase.cs

Refactored randomizers to access the sole active scenario through the static activeScenario property.

Refactored Randomizers to use static activeScenario property

---

com.unity.perception/CHANGELOG.md
com.unity.perception/Documentation~/Randomization/Scenarios.md
com.unity.perception/Editor/Randomization/Editors/RunInUnitySimulationWindow.cs
com.unity.perception/Editor/Randomization/Editors/ScenarioBaseEditor.cs
com.unity.perception/Editor/Randomization/Uxml/ScenarioBaseElement.uxml
com.unity.perception/Runtime/Randomization/Scenarios/Scenario.cs
com.unity.perception/Runtime/Randomization/Scenarios/ScenarioBase.cs
com.unity.perception/Runtime/Randomization/Scenarios/UnitySimulationScenario.cs
com.unity.perception/Tests/Runtime/Randomization/ScenarioTests.cs

**NOTICE**: Merge the [global-seed PR](https://github.com/Unity-Technologies/com.unity.perception/pull/142) first before merging this PR.
This PR extends the serialization functionality of the Scenario's constants configuration to serialize samplers in randomizers along with the original list of scenario constants.
Other changes include improving UI and console feedback for configuration file serialization and deserialization. The UI will now ping the newly created configuration file in the project window when it is created. When deserializing a configuration file, a notification will appear in the console informing users that all constants and randomizer changes are undo-able.
Configuration files will no longer be deserialized automatically in playmode (users must manually click the …

Serializing samplers with scenario constants configuration

---

com.unity.perception/Documentation~/Randomization/Samplers.md

Updated sampler docs to explain the new centralized scenario seeding strategy.

Added sampler seeding documentation

---

com.unity.perception/Editor/Randomization/Editors/ScenarioBaseEditor.cs
com.unity.perception/Editor/Randomization/Uss/Styles.uss
com.unity.perception/Editor/Randomization/Uxml/Randomizer/RandomizerList.uxml
com.unity.perception/Editor/Randomization/Uxml/ScenarioBaseElement.uxml
com.unity.perception/Runtime/Randomization/Scenarios/FixedLengthScenario.cs
com.unity.perception/Runtime/Randomization/Scenarios/ScenarioConstants.cs
com.unity.perception/Runtime/Randomization/Scenarios/UnitySimulationScenarioConstants.cs

- Revised scenario constants UI code to add tooltip capability
- Added tooltips for all fixed length scenario constants
- Added info box about order of randomization execution
- None

UI improvements for scenario inspector

---

README.md

A couple more adjustments to branding

---

com.unity.perception/Editor/Randomization/Editors/RunInUnitySimulationWindow.cs

- N/A
**Editor Version Target (i.e. 19.3, 20.1)**: 2019.4.16
- N/A
- N/A
- The progress bar always loses focus. Did some googling but there is apparently not much we can do about it.
**Notes + Expectations**: 
- N/A

Added progress bar for USim upload 

---

com.unity.perception/CHANGELOG.md
com.unity.perception/Runtime/GroundTruth/Labelers/JointLabel.cs
com.unity.perception/Runtime/GroundTruth/Labeling/Labeling.cs
com.unity.perception/Runtime/Randomization/Scenarios/FixedLengthScenario.cs

This PR refactors the AddComponentMenu paths of a few MonoBehaviours.

Perception add component menu update

---

com.unity.perception/Runtime/GroundTruth/Labelers/InstanceSegmentationLabeler.cs

Fixed instance segmentation labeler capturing on every frame

---

com.unity.perception/CHANGELOG.md

Added additional upgrade instructions to changelog.

Changelog upgrade notes for 0.7.0

---

com.unity.perception/Samples~/Human Pose Estimation/Models and Animations/Idle.fbx.meta
com.unity.perception/Samples~/Human Pose Estimation/Models and Animations/Player.fbx.meta
com.unity.perception/Samples~/Human Pose Estimation/Models and Animations/PutGlassesOn.fbx.meta
com.unity.perception/Samples~/Human Pose Estimation/Models and Animations/Run.fbx.meta
com.unity.perception/Samples~/Human Pose Estimation/Models and Animations/TakeObjectAttempt.fbx.meta
com.unity.perception/Samples~/Human Pose Estimation/Models and Animations/TakeObjects.fbx.meta
com.unity.perception/Samples~/Human Pose Estimation/Models and Animations/Walk.fbx.meta

added meta files for HPE samples

---

com.unity.perception/package.json

Quick PR to update the capture version to the latest patch.

Update capture dependency version

---

com.unity.perception/Documentation~/HPETutorial/TUTORIAL.md
com.unity.perception/Documentation~/Tutorial/Phase2.md

Added small info paragraph about the "Optimize Game Objects" checkbox in the rig import options.

HPE tutorial patch

---

README.md

Doc change only.  Adding link to main CV hub.

Adding link to computer vision hub

---

com.unity.perception/CHANGELOG.md
com.unity.perception/Editor/Randomization/VisualElements/Parameter/ParameterElement.cs

Now allows 'Add Folder' to append on already present elements
See above

Fixed parameter element editor

---

com.unity.perception/Documentation~/Tutorial/Phase1.md
com.unity.perception/Documentation~/Tutorial/Phase3.md

Added a troubleshooting note regarding the docker commands.

tutorial patch - docker troubleshooting note

---

com.unity.perception/Documentation~/PerceptionCamera.md

Updates to perception documentation

---

README.md

Adding supported version badges to README.md

Adding supported version badges

---

com.unity.perception/Runtime/GroundTruth/Labelers/BoundingBox3DLabeler.cs

Tentative fixes for bounding box 3d calculation issues

Fix bbox3d calculation

---

com.unity.perception/CHANGELOG.md
com.unity.perception/Runtime/GroundTruth/InstanceIdToColorMapping.cs
com.unity.perception/Tests/Runtime/GroundTruthTests/InstanceIdToColorMappingTests.cs

Before:
After:
(p.s. not a totally fair test, as the labeling scheme changed a bit between these images, but you get the idea)

Increasing color variety in instance segmentation.

---

com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/BackgroundObjectPlacementRandomizer.cs
com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/ColorRandomizer.cs
com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/ForegroundObjectPlacementRandomizer.cs
com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/HueOffsetRandomizer.cs
com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/RotationRandomizer.cs
com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/SunAngleRandomizer.cs
com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/TextureRandomizer.cs

- Added tooltips to all sample randomizer properties.
- Changed the max value for day sampler in the sung angle randomizer from 365 to 364, which seems to be the initial intended value.

Added tooltips to sample randomizers

---

TestProjects/PerceptionHDRP/Packages/packages-lock.json
com.unity.perception/CHANGELOG.md
com.unity.perception/Documentation~/GroundTruth/KeypointLabeler.md
com.unity.perception/Documentation~/HPTutorial/TUTORIAL.md
com.unity.perception/Documentation~/PerceptionCamera.md
com.unity.perception/Editor/GroundTruth/JointLabelEditor.cs
com.unity.perception/Editor/GroundTruth/JointLabelEditor.cs.meta
com.unity.perception/Runtime/GroundTruth/Labelers/BoundingBox3DLabeler.cs
com.unity.perception/Runtime/GroundTruth/Labelers/KeypointLabeler.cs
com.unity.perception/Runtime/GroundTruth/Labelers/KeypointObjectFilter.cs
com.unity.perception/Runtime/GroundTruth/Labelers/KeypointObjectFilter.cs.meta
com.unity.perception/Runtime/GroundTruth/RenderPasses/HdrpPasses/GroundTruthPass.cs
com.unity.perception/Runtime/GroundTruth/RenderPasses/HdrpPasses/InstanceSegmentationPass.cs
com.unity.perception/Runtime/GroundTruth/RenderPasses/HdrpPasses/LensDistortionPass.cs
com.unity.perception/Runtime/GroundTruth/RenderPasses/HdrpPasses/SemanticSegmentationPass.cs
com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/AnimationRandomizer.cs
com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/BackgroundObjectPlacementRandomizer.cs
com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/ColorRandomizer.cs
com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/ForegroundObjectPlacementRandomizer.cs
com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/HueOffsetRandomizer.cs
com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/RotationRandomizer.cs
com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/SunAngleRandomizer.cs
com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/TextureRandomizer.cs
com.unity.perception/Runtime/Unity.Perception.Runtime.asmdef
com.unity.perception/Tests/Runtime/GroundTruthTests/BoundingBox3dTests.cs
com.unity.perception/Tests/Runtime/GroundTruthTests/KeypointGroundTruthTests.cs
com.unity.perception/package.json

This PR merges all changes from 0.8.0-preview.1_staging as of 3/26/21 8am
**Tests Added**: Various
**Core Scenario Tested**: Various

0.8.0 changes -> master

---

com.unity.perception/Runtime/GroundTruth/Labelers/CameraLabeler.cs
com.unity.perception/Runtime/GroundTruth/Labeling/LabelManager.cs
com.unity.perception/Runtime/GroundTruth/PerceptionCamera.cs
com.unity.perception/Runtime/Randomization/Scenarios/FixedLengthScenario.cs

- This builds on the addressable POC by adding code to the scenario for initializing label configs and labelers at the end of the first iteration. 

some changes to make runtime labeling and label config creation work

---

com.unity.perception/Editor/Randomization/Editors/RunInUnitySimulationWindow.cs
com.unity.perception/Runtime/Randomization/Scenarios/ScenarioBase.cs

Stapled ScenarioBase's Iteration loop back together

stapled scenario back together

---

com.unity.perception/Documentation~/Tutorial/Phase1.md
com.unity.perception/Documentation~/Tutorial/Phase3.md

Small updates and polish for the Perception tutorial

---

.yamato/environments.yml
.yamato/upm-ci-performance.yml
.yamato/upm-ci-testprojects.yml
com.unity.perception/CHANGELOG.md
com.unity.perception/package.json

This PR upgrades the capture package dependency to the latest version to fix warnings about missing meta files.

Upgrade capture package dependency

---

com.unity.perception/package.json

This version fixes the issue where RGB captures have no post processing applied.

Updated capture package dependency

---

com.unity.perception/CHANGELOG.md
com.unity.perception/Editor/GroundTruth/PerceptionCameraEditor.cs
com.unity.perception/Runtime/GroundTruth/SimulationState.cs

Output directory

---

README.md
com.unity.perception/Documentation~/HPTutorial/TUTORIAL.md
com.unity.perception/Documentation~/Tutorial/Phase1.md

Moved the community and support paragraph up to make it more visible. Also slightly modified the paragraph title and changed some fonts to bold face.
Added a note to the beginning of the tutorial about using the forum or the issues page.

Made Community and Support paragraph on frontpage more noticeable

---

com.unity.perception/Documentation~/HPTutorial/TUTORIAL.md

A small fix for the keypoint labeling tutorial

---

com.unity.perception/Runtime/GroundTruth/Labelers/BoundingBox3DLabeler.cs

fix the exception typo, should be "3D" not "2D"

---

TestProjects/PerceptionHDRP/Assets/Scenes/SampleScene.unity
TestProjects/PerceptionURP/Assets/Scenes/SampleScene.unity

Reverting SampleScene changes made on Keypoint Labeling branch. Fixing some issues with missing prefabs and lighting
**Editor Version Target**:2020.3

Reverting SampleScene changes

---

com.unity.perception/CHANGELOG.md
com.unity.perception/Runtime/GroundTruth/Labeling/IdLabelConfig.cs

Closes #10
**Tests Added**: None
**Core Scenario Tested**: None
**At Risk Areas**: None

Make GetAnnotationSpecification() public, by popular demand.

---

com.unity.perception/CHANGELOG.md
com.unity.perception/Documentation~/FAQ/FAQ.md
com.unity.perception/Documentation~/PerceptionCamera.md
com.unity.perception/Runtime/GroundTruth/Labelers/BoundingBox3DLabeler.cs

3d bbox doc t2
