Unity-Technologies/com.unity.perception

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/GroundTruth/PerceptionCamera.cs
Fix for aisv-614. Fixes issue with RGB images not being captured and also errors being thrown every frame. Solution consists of removing our own version of flipY and use the one provided to us by capture camera.
<br>
<br>
<br>
<br>
=> Aisv614 fix

TestProjects/PerceptionHDRP/Assets/csc.rsp, TestProjects/PerceptionHDRP/Assets/csc.rsp.meta, TestProjects/PerceptionURP/Assets/ExampleScripts/CustomAnnotationAndMetricReporter.cs, TestProjects/PerceptionURP/Assets/csc.rsp, TestProjects/PerceptionURP/Assets/csc.rsp.meta, com.unity.perception/CHANGELOG.md, com.unity.perception/Documentation~/DatasetCapture.md, com.unity.perception/Runtime/GroundTruth/Labelers/SemanticSegmentationLabeler.cs, com.unity.perception/Runtime/GroundTruth/PerceptionCamera.cs, com.unity.perception/Runtime/GroundTruth/SimulationState_Json.cs, com.unity.perception/Tests/Runtime/GroundTruthTests/SegmentationGroundTruthTests.cs
Fix warnings in the package when using the latest com.unity.simulation.core package. Also fixes other warnings in the tests and test projects.
Enabled warnings as errors in both test projects using csc.rsp files so that we do not regress in warnings going forward.
Enabled warnings as errors in the test projects.
<br>
<br>
<br>
**At Risk Areas**: None
<br>
=> Fix warnings

com.unity.perception/Runtime/GroundTruth/Labelers/SemanticSegmentationLabeler.cs, com.unity.perception/Runtime/GroundTruth/Resources/SemanticSegmentation.shader, com.unity.perception/Runtime/GroundTruth/SemanticSegmentationCrossPipelinePass.cs, com.unity.perception/Tests/Runtime/GroundTruthTests/SegmentationGroundTruthTests.cs
Fixing wrong colors in semantic segmentation due to sRGB conversion by changing the shader parameter to a Vector, bypassing sRGB conversion altogether.
Fixes #44 
Updated semantic segmentation tests to use a color that would be affected by sRGB <->Linear color conversions
<br>
<br>
<br>
<br>
=> Fixing wrong colors in semantic segmentation 

com.unity.perception/Runtime/GroundTruth/Labelers/Visualization/Resources/SegRemoveBackgroundShader.shader
Capped the max opacity allowed in the shader to an extremely high value (0.995) to stop a weird issue caused by alpha being set to 1.0
<br>
<br>
<br>
<br>
=> Segmentation Alpha Bug Fix

com.unity.perception/Runtime/GroundTruth/DatasetCapture.cs, com.unity.perception/Runtime/GroundTruth/PerceptionCamera.cs, com.unity.perception/Runtime/GroundTruth/SimulationState.cs, com.unity.perception/Tests/Runtime/GroundTruthTests/PerceptionCameraIntegrationTests.cs
Do not generate any empty folders if the PerceptionCamera is never enabled and no other dataset generation APIs are called.
Fixes AISV-719
Added test
<br>
<br>
<br>
<br>
=> Do not generate any empty folders if the PerceptionCamera is never enabled

TestProjects/PerceptionURP/Assets/Scenes/SampleScene.unity, com.unity.perception/Runtime/GroundTruth/PerceptionCamera.cs
Non-development players were getting into a bad codepath where `showVisualizations` was true but the visualizations themselves were not initialized. This was causing exceptions in OpenGL for unknown reasons. This PR fixes the inconsistency.
I couldn't figure out how to add tests for this though, since I'm not sure how to run tests in OpenGL. Just manual testing for now.
<br>
<br>
Tested editor, development player, non-development player with visualizations enabled and disabled on each. 
<br>
<br>
=> Fix exceptions in non-development players

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/GroundTruth/DatasetCapture.cs, com.unity.perception/Runtime/GroundTruth/Labelers/BoundingBoxLabeler.cs, com.unity.perception/Runtime/GroundTruth/SimulationState.cs, com.unity.perception/Tests/Runtime/GroundTruthTests/DatasetCaptureTests.cs, com.unity.perception/Tests/Runtime/GroundTruthTests/PerceptionCameraIntegrationTests.cs, com.unity.perception/Tests/Runtime/GroundTruthTests/TestHelper.cs
This fixes a bug where the dataset will include bounding boxes for objects whose labels do not match the label config. These objects were reported as label 0 with a `null` label name.
With this change, these objects are no longer reported.
Added test for objects whose labels do not match the label config.
=> No boxes on unmatching objects

TestProjects/PerceptionHDRP/Packages/manifest.json, TestProjects/PerceptionHDRP/Packages/packages-lock.json, TestProjects/PerceptionURP/Packages/manifest.json, TestProjects/PerceptionURP/Packages/packages-lock.json, com.unity.perception/package.json
Small change - upgrading to simulation.capture to preview.13 to address intermittent shader compilation error on URP projects.
=> Updating simulation.capture to preview.13

com.unity.perception/Runtime/GroundTruth/LensDistortionCrossPipelinePass.cs
This change resolves the issue with lens distortion in URP where the post processing flag has been set for a camera, but no global override is present to actually set the lens distortion parameters. Also nice-ifyed the logic a bit. 
=> Bugfix: Resolving issue with Lens Distortion in URP when Post Processing enabled, but no global override

.yamato/environments.yml, com.unity.perception/CHANGELOG.md, com.unity.perception/Documentation~/Tutorial/Phase1.md, com.unity.perception/Tests/Editor/DatasetCaptureEditorTests.cs
- Disabled 2020.1 tests for this release
- Reset simulation state at the beginning of the SimpleData_GeneratesFullDataset_OnExitPlaymode test to prevent upstream tests from affecting the outcome
=> Disabled 2020.1 tests for 0.5.0 release

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/Randomization/Scenarios/USimScenario.cs
This PR patches a bug in the USimScenario class that resulted in the scenario iteration incorrectly being offset before the Unity Simulation app-params had a chance to deserialize.
=> USim scenario iteration offset fix

.yamato/environments.yml, .yamato/promote.yml, .yamato/upm-ci-full.yml, com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/Randomization/Scenarios/ScenarioBase.cs
In the unity editor and local players, the perception package cannot output the first frame of the simulation, so the randomization scenario class will skip the first frame. This is not the case on Unity Simulation. This PR introduces a check that will allow randomized perception projects to not skip the first frame if running on Unity Simulation.
=> Fixed Unity Simulation nodes generating an empty first image

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/Randomization/Parameters/CategoricalParameter.cs
Fixed enumeration in the CategoricalParameter.categories property
=> Categorical parameter enumeration fix

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/Randomization/Samplers/SamplerTypes/NormalSampler.cs, com.unity.perception/Runtime/Randomization/Samplers/SamplerTypes/UniformSampler.cs
Uniform and normal samplers will now serialize their random seeds. This is to prevent Unity's serialization tools from zeroing out the sampler's random state in the editor. This change will allow users to utilize samplers from Edit Mode without the Unity.Mathematics.Random struct within the sampler from throwing an error for having a zeroed out initial state.
=> Uniform and normal samplers now serialize their random seeds

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/BackgroundObjectPlacementRandomizer.cs, com.unity.perception/Runtime/Randomization/Scenarios/ScenarioBase.cs, com.unity.perception/Tests/Runtime/Randomization/ScenarioTests.cs
ScenarioBase's GenerateRandomSeedFromIndex() method now correctly hashes the current scenario iteration into the generated random seed.
=> Fixed GenerateRandomSeedFromIndex method

.yamato/upm-ci-testprojects.yml
This PR enables rerunning failures in our UTR-based tests using `--reruncount=2`. Reruns will trigger notifications 
=> Enabling rerunning failures on yamato

.yamato/environments.yml, com.unity.perception/CHANGELOG.md, com.unity.perception/Editor/Randomization/Editors.meta, com.unity.perception/Editor/Randomization/Editors/ScenarioBaseEditor.cs.meta, com.unity.perception/Editor/Randomization/PropertyDrawers.meta, com.unity.perception/Editor/Randomization/PropertyDrawers/ColorHsvaDrawer.cs.meta, com.unity.perception/Editor/Randomization/PropertyDrawers/ParameterDrawer.cs.meta, com.unity.perception/Editor/Randomization/StaticData.cs.meta, com.unity.perception/Editor/Randomization/Uss.meta, com.unity.perception/Editor/Randomization/Uxml.meta, com.unity.perception/Editor/Randomization/Uxml/Parameter/ParameterDrawer.uxml.meta, com.unity.perception/Editor/Randomization/VisualElements.meta, com.unity.perception/Editor/Randomization/VisualElements/Parameter.meta, com.unity.perception/Editor/Randomization/VisualElements/Parameter/CategoricalOptionElement.cs.meta, com.unity.perception/Editor/Randomization/VisualElements/Parameter/ColorHsvaField.cs.meta, com.unity.perception/Editor/Randomization/VisualElements/Parameter/DrawerParameterElement.cs.meta, com.unity.perception/Editor/Randomization/VisualElements/Parameter/ParameterElement.cs.meta, com.unity.perception/Editor/Randomization/VisualElements/Randomizer.meta, com.unity.perception/Editor/Randomization/VisualElements/Randomizer/AddRandomizerMenu.cs.meta, com.unity.perception/Editor/Randomization/VisualElements/Randomizer/RandomizerElement.cs.meta, com.unity.perception/Editor/Randomization/VisualElements/Randomizer/RandomizerList.cs.meta, com.unity.perception/Editor/Randomization/VisualElements/Randomizer/RandomizerReorderingIndicator.cs.meta, com.unity.perception/Editor/Randomization/VisualElements/Sampler.meta, com.unity.perception/Editor/Randomization/VisualElements/Sampler/FloatRangeElement.cs.meta, com.unity.perception/Editor/Randomization/VisualElements/Sampler/RandomSeedField.cs.meta, com.unity.perception/Editor/Randomization/VisualElements/Sampler/SamplerElement.cs.meta, com.unity.perception/Runtime/Randomization/Parameters/ParameterTypes/NumericParameters/ColorParameters.meta, com.unity.perception/Runtime/Randomization/Randomizers.meta, com.unity.perception/Tests/Runtime/Randomization/RandomizerTests.meta
Many .meta files seemingly in the middle of merge conflicts have been identified within the perception package and rebuilt. This process has fixed the supposed memory leak bug previously encountered when adding the perception package to a 2020.1 project.
This PR will also reenable Unity 2020.1 per commit tests.
**Editor Version Target**: 2019.4 and 2020.1
=> Removed corrupted meta files

com.unity.perception/Runtime/GroundTruth/SimulationState.cs, com.unity.perception/Tests/Runtime/GroundTruthTests/DatasetCaptureTests.cs, com.unity.perception/package.json
Newtonsoft JArray.FromObject(values, m_AnnotationSerializer) API call uses LINQ under the hood which is not supported on IL2CPP. It throws an exception at runtime.
Replacing this API call with using DatasetJsonUtility instead.
Manually verified the fix on cloud rendering buidltarget 
**Core Scenario Tested**: Boundingbox annotation report serialization at the end of the simulation run.
**At Risk Areas**: Boudingbox annotation reporting.
**Notes + Expectations**: Bounding annotation reporting should work with IL2CPP scripting backend on all platforms.
=> Report annotation result fix il2cpp

com.unity.perception/CHANGELOG.md, com.unity.perception/Editor/Randomization/VisualElements/Randomizer/RandomizerList.cs
The randomizer list inspector UI now updates appropriately when a user clicks undo.
**Editor Version Target**: 2019.34
=> Added undo callback to refresh randomizer list UI

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/GroundTruth/Labelers/Visualization/OverlayPanel.cs
Fixed an issue where the overlay panel would display a full screen semi-transparent image over the entire screen when the overlay panel is disabled in the UI
**Notes + Expectations**: 
- [ x] - Updated docs
- [ x] - Updated changelog
=> Fixed overlay panel bug

com.unity.perception/Editor/GroundTruth/SemanticSegmentationLabelConfigEditor.cs, com.unity.perception/Editor/GroundTruth/Uxml/ColoredLabelElementInLabelConfig.uxml
Added hex color representation to semantic segmentation label config UI. These labels are purely for display and cannot be interacted with. The purpose of the label is to help the user verify whether the colours are different or not.
=> Hex color representation in semantic segmentation label config UI

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/Randomization/Parameters/CategoricalParameter.cs, com.unity.perception/Runtime/Randomization/Parameters/ParameterValidationException.cs, com.unity.perception/Runtime/Randomization/Randomizers/RandomizerTagManager.cs, com.unity.perception/Runtime/Randomization/Samplers/SamplerTypes/ConstantSampler.cs, com.unity.perception/Runtime/Randomization/Samplers/SamplerTypes/NormalSampler.cs, com.unity.perception/Runtime/Randomization/Samplers/SamplerTypes/UniformSampler.cs, com.unity.perception/Runtime/Randomization/Samplers/SamplerUtility.cs, com.unity.perception/Runtime/Randomization/Scenarios/ScenarioBase.cs, com.unity.perception/Tests/Runtime/Randomization/RandomizerTests/ExampleTag.cs, com.unity.perception/Tests/Runtime/Randomization/RandomizerTests/RandomizerTagTests.cs
Randomizer tags support inheritance. A user can query tag of a specific type, or of any type that inherits from it.
Modified TagQueryFindsCorrectNumberOfGameObjects test to test that inheritance works properly
=> Randomizer tag inheritence

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/GroundTruth/PerceptionCamera.cs, com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/BackgroundObjectPlacementRandomizer.cs, com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/ForegroundObjectPlacementRandomizer.cs, com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Utilities/GameObjectOneWayCache.cs, com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Utilities/GameObjectOneWayCache.cs.meta
This PR makes it so the simulation continues to run when the editor is not focused and fixes a memory leak and crash at the end of a long simulation using the background and foreground placement randomizers.
Turns out instantiating and deleting millions of objects causes a massive hang at the end of play mode while the graphics system is cleaning up its memory. My fix is to insert the object caching we created for SynthDet.
Did not add tests, as the repro is inconsistent and would take too long to run.
**Core Scenario Tested**: Tested in NeuralPocket customer project
=> Fixing crash and memory leak on long simulations

com.unity.perception/Runtime/GroundTruth/PerceptionCamera.cs, com.unity.perception/Runtime/Unity.Perception.Runtime.asmdef
FlipY is correct by default in preview.16 and later
1. The latest capture package accesses and uses the render targets that URP/HDRP create. This means that even if the camera doesn't have a target, it is still rendering to a RT, and generally won't need to be flipped.  
2. Take a look at the second commit in this PR. I tested with anyVisualizing = false, and it seems to work correctly now.
The latest capture package will support 2019.4 onwards.
No tests have been added in the PR, but the capture package has many tests for validating orientation for each pipeline.
Tested with PerceptionURP, PerceptionHDRP
**Notes + Expectations**: 
Expectation is that with this change, upgrading to .16 will cause no output changes with the perception package.
=> Fix for breaking change in capture refactor.

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/Randomization/Scenarios/ScenarioBase.cs, com.unity.perception/Tests/Editor/RandomizerEditorTests.cs, com.unity.perception/Tests/Editor/RandomizerEditorTests.cs.meta
This PR fixes a bug where the OnCreate() method on Randomizers was incorrectly called in edit-mode when a user adds a randomizer to a scenario.
**Editor Version Target)**: 2019.4
Added an edit-mode test to confirm that OnCreate() is not called when adding a randomizer to a scenario in edit-mode.
=> On create randomizer fix

com.unity.perception/Runtime/Randomization/Randomizers/Randomizer.cs, com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/BackgroundObjectPlacementRandomizer.cs, com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/ForegroundObjectPlacementRandomizer.cs, com.unity.perception/Runtime/Randomization/Randomizers/RandomizerTag.cs, com.unity.perception/Runtime/Randomization/Randomizers/RandomizerTagManager.cs, com.unity.perception/Runtime/Randomization/Scenarios/ScenarioBase.cs, com.unity.perception/Tests/Runtime/Randomization/RandomizerTests/RandomizerTagTests.cs
This PR decouples the RandomizerTagManager from the ScenarioBase class to ensure that RandomizerTags are properly tracked even when the active scenario is disabled.
=> Decouple RandomizerTagManager from Scenarios

com.unity.perception/CHANGELOG.md, com.unity.perception/Editor/Randomization/Uxml/Randomizer/RandomizerList.uxml, com.unity.perception/Editor/Randomization/VisualElements/Randomizer/AddRandomizerMenu.cs, com.unity.perception/Editor/Randomization/VisualElements/Randomizer/RandomizerList.cs, com.unity.perception/Runtime/Randomization/Scenarios/ScenarioBase.cs
Fixed a bug where removing all randomizers from a scenario caused the randomizer container UI element to overflow over the end of Scenario component UI
=> Remove all randomizers bug

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/BackgroundObjectPlacementRandomizer.cs, com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/ForegroundObjectPlacementRandomizer.cs, com.unity.perception/Runtime/Randomization/Samplers/SamplerState.cs, com.unity.perception/Runtime/Randomization/Samplers/SamplerState.cs.meta, com.unity.perception/Runtime/Randomization/Samplers/SamplerTypes/AnimationCurveSampler.cs, com.unity.perception/Runtime/Randomization/Samplers/SamplerTypes/NormalSampler.cs, com.unity.perception/Runtime/Randomization/Samplers/SamplerTypes/UniformSampler.cs, com.unity.perception/Runtime/Randomization/Scenarios/Scenario.cs, com.unity.perception/Runtime/Randomization/Scenarios/ScenarioBase.cs, com.unity.perception/Tests/Runtime/Randomization/SamplerTests/SamplerTestsBase.cs, com.unity.perception/Tests/Runtime/Randomization/ScenarioTests.cs
With this PR, the random state tracked inside scenarios has been moved to its own publicly accessible static class. This will allow samplers and parameters to be used without requiring a scenario to be active in the scene.
=> Isolate sampler random state from scenarios

com.unity.perception/Editor/GroundTruth/PerceptionCameraEditor.cs, com.unity.perception/Runtime/GroundTruth/SimulationState.cs
* Added two buttons to the Perception Camera's inspector for opening the latest output folder and copying its path to clipboard.
* Although the buttons are added to the Perception Camera, the directory is the same across all sensors for each run. It changes on each run. But since most (if not all) of our users seem to use a single camera, this solution should be OK for now.
=> Output dir shortcut

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/TextureRandomizer.cs
This PR adds a compiler check to the TextureRandomizer to use a different material property name in HDRP vs URP.
=> Make TextureRandomizer compatible with HDRP

com.unity.perception/CHANGELOG.md, com.unity.perception/Samples~/Tutorial Files/Background Objects/Materials/prototyping_texture_alignment_01.mat
This PR enables the "GPU instancing" boolean in the sample material's inspector to fix a data generation bug in the perception tutorial. When the editor is first opened, and a user generates a dataset by clicking the play button, the first generated image had duplicated textures and hue offsets for all background objects.
=> Enabled GPU instancing on sample material

com.unity.perception/CHANGELOG.md
Updated the change log to add a known issue with 3d bbox and skinned mesh renderers
=> Updated change log

com.unity.perception/Editor/GroundTruth/CameraLabelerDrawer.cs
This fixes Pose State Config not showing up in the editor in 2019.4. The fix was to use an overload of `EditorGUI.PropertyField` that enables drawing children (not sure why this isn't default). The reason it only occurs on 2019.4 is that the default editor for arrays changed in 2020 to a nicer control which apparently does not respect this child drawing flag.
**Tests Added**: None. GUI work.
**Core Scenario Tested**: Tested the UI on 2019.4 and 2020.2
=> Fix Post State Configs not showing up in 2019.4

com.unity.perception/CHANGELOG.md, com.unity.perception/package.json
This PR upgrades the Unity Simulation Capture package dependency to 0.0.10-preview.18 and Unity Simulation Core to 0.0.10-preview.22
=> Upgrade capture dependencies

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/Randomization/Scenarios/UnitySimulationScenario.cs
This PR corrects the math offsetting the iteration index of each Unity Simulation instance directly after they deserialize their app-params.
=> Fixed Unity Simulation per instance iteration offset

com.unity.perception/CHANGELOG.md, com.unity.perception/package.json
Updating the package version to 0.7.0-preview.2 for a patch release.
=> Updating package version to 0.7.0-preview.2

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/GroundTruth/PerceptionCamera.cs, com.unity.perception/Runtime/GroundTruth/PerceptionCamera_InstanceSegmentation.cs, com.unity.perception/Tests/Editor/PerceptionCameraEditorTests.cs, com.unity.perception/Tests/Runtime/GroundTruthTests/SegmentationGroundTruthTests.cs, com.unity.perception/Tests/Runtime/GroundTruthTests/VisualizationTests.cs
Fixes bug reported by ANT where disabled PerceptionCameras cause the active PerceptionCamera to not produce proper 2d bounding boxes in HDRP.
The reason was our in our use of CustomPasses. Only one CustomPass of a given type may run at any one time, and since CustomPasses were initialized in PerceptionCamera.Awake(), the disabled PerceptionCameras' CustomPasses were overwriting the enabled one. This is a bigger issue to be addressed when we go to properly support multiple simultaneous cameras. This fix moves the initialization logic from Awake into Start to address the immediate issue with disabled PerceptionCameras.
A few other changes needed to be made to adjust for the timing of the logic. In the process I made RGB capture work for multiple cameras at once to resolve a new test …
=> Fix multiple cameras

com.unity.perception/Documentation~/HPTutorial/TUTORIAL.md
Since there will be some time until the 0.7.0-preview.3 patch comes out, this PR reverts a couple of things from the previous renaming PR:
- Reverted package version requirement to preview.2
- Reverted mentions of samples’ name back to “Human Pose Estimation”
=> Reverted certain things in HP tutorial

com.unity.perception/CHANGELOG.md, com.unity.perception/Editor/Randomization/Uss/Styles.uss, com.unity.perception/Editor/Randomization/VisualElements/Parameter/CategoricalOptionElement.cs, com.unity.perception/Editor/Randomization/VisualElements/Parameter/ParameterElement.cs
This PR fixes two issues with the uniform toggle on categorical parameters that were discovered in HDRP:
1. An null reference error was appearing when attempting to remove the extraneous label added to categorical option UI elements. This was fixed by using USS selectors instead of C# to style away labels instead of explicitly removing them.
2. The uniform toggle wasn't being initialized properly, causing it to toggle to the opposite state on occasion. This has been fixed by using a stateful approach to modifying the UI instead of a toggle approach.
=> Fixed categorical parameter uniform toggle issues in HDRP

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/Randomization/Randomizers/RandomizerTag.cs
Changed randomizer tags to use OnEnable and OnDisable. This allows for the user to enable/disable them via a toggle in the Unity Editor. Tested and verified that this works before game play and during game play.
=> Randomizer tags can be enabled via editor

com.unity.perception/CHANGELOG.md, com.unity.perception/Documentation~/Schema/Synthetic_Dataset_Schema.md, com.unity.perception/Runtime/GroundTruth/Labelers/KeypointLabeler.cs, com.unity.perception/Tests/Runtime/GroundTruthTests/KeypointGroundTruthTests.cs
Fixes for both 1160 & 1161. Labeled assets with all of their keypoints completely off screen are not reported to the captures.json file. If a labeled asset is at least partially on screen (or more precise at least 1 of its keypoints are on screen) then all the keypoints will be marked with the following values: 0 => keypoint does not exist in the model or is off screen, 1 => keypoint exists and is on screen, but is occluded by some other object, 2 => keypoint exists and is visible.
New correctness tests have been included to test all of these states.
=> Keypoint occlusion

.yamato/upm-ci-full.yml
Removing code coverage from per-commit tests. Code coverage fails from time to time, and it isn't necessary to run in the PR process since it is only used for manual checking of quality.
=> Remove code coverage generation from per-commit CI

com.unity.perception/Editor/GroundTruth/PerceptionCameraEditor.cs
The displayHeader flag was set to false for the list of labelers in PerceptionCamera. Weirdly, it was still displaying in older Unity versions before 2020.2.
=> Fixed a perception camera editor UI bug

com.unity.perception/Tests/Editor/UIElementsEditorUtilitiesTests.cs
A test has a warning about unused variable, pragma'ed it out
=> Removed test error preventing Unity from playing

com.unity.perception/CHANGELOG.md, com.unity.perception/package.json
Upgraded com.unity.simulation.capture package dependency to integrate new changes that prevent the API updater from looping infinitely when opening the project settings window on new Windows URP projects.
=> Updated capture dependency

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/GroundTruth/Labelers/KeypointLabeler.cs
A quick fix for an index out of bounds error that could occur if a keypoint template file was not set up properly
=> Quick fix for a out of range error that could occur

com.unity.perception/Runtime/GroundTruth/Labelers/InstanceSegmentationLabeler.cs, com.unity.perception/Runtime/GroundTruth/Labelers/SemanticSegmentationLabeler.cs, com.unity.perception/Runtime/GroundTruth/PerceptionCamera.cs
Remove AsyncRequest frame limiter to prevent hanging on image encoding in projects with little rendering and scene setup like SynthDet V2. Doubles frame rate in the editor in this case.
**Tests Added**: None. Existing tests should cover it.
**Core Scenario Tested**: SynthDet V2. Automated tests.
=> Remove waits for 2x perf

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/GroundTruth/IGroundTruthGenerator.cs, com.unity.perception/Runtime/GroundTruth/InstanceIdToColorMapping.cs, com.unity.perception/Runtime/GroundTruth/Labelers/KeypointLabeler.cs, com.unity.perception/Runtime/GroundTruth/Labeling/LabelEntryMatchCache.cs, com.unity.perception/Runtime/GroundTruth/Labeling/LabelManager.cs, com.unity.perception/Runtime/GroundTruth/RenderPasses/CrossPipelinePasses/GroundTruthCrossPipelinePass.cs, com.unity.perception/Runtime/GroundTruth/RenderPasses/CrossPipelinePasses/InstanceSegmentationCrossPipelinePass.cs, com.unity.perception/Runtime/GroundTruth/RenderPasses/CrossPipelinePasses/LensDistortionCrossPipelinePass.cs, com.unity.perception/Runtime/GroundTruth/RenderPasses/CrossPipelinePasses/SemanticSegmentationCrossPipelinePass.cs, com.unity.perception/Runtime/GroundTruth/RenderPasses/HdrpPasses/GroundTruthPass.cs, com.unity.perception/Tests/Runtime/GroundTruthTests/KeypointGroundTruthTests.cs
- Added the ClearMaterialProperties method to IGroundTruthGenerator 
- Fixed an issue in keypoint groundtruth tests where passing a list of keypoints by reference could cause issues with data being overwrriten if more than one frame was tested.
- Added test for keypoint ground truth generation with a disabled labeling component (plus switching at runtime)
=> Addressing feedback on a previous PR for disabling labeling components

com.unity.perception/Documentation~/Schema/Synthetic_Dataset_Schema.md
The summary for the 3d bounding box states the coordinates are from the sensor's reference frame, but the string for the translational component says it's global.  I *think* this is just a typo in the doc, so correcting the description to match the summary for this type of entry.
=> Amending dataset schema to describe correct coordinate system

com.unity.perception/Editor/Randomization/Editors/RunInUnitySimulationWindow.cs
Updated the RunInUnitySimulationWindow script to add support for cloudrendering build.
The changes will build for CloudRendering build target when the user is on that build target and check for sysparam selection.
It will prompt if the right sysparam is not selected by the developer (with GPU) from the dropdown.
Verified locally by running simulation with cloudrendering build target.
Verfied the dialog with different sysparam selection
Unity Simulation Build and Run
**Notes + Expectations**: 
- When switched to cloud rendering build target, Build and Run option should create a headless build with cloud rendering build target.
- If appropriate sysparam is not selected, the …
=> Cloud rendering support

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/Randomization/Samplers/SamplerUtility.cs
Fixed a bug where random values really close to either 0 or 1 (around 7 decimal digits) the normal randomizer could return values outside of the min/max values.
=> A fix that prevents normal sampler returning values outside of min max

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/GroundTruth/RenderPasses/HdrpPasses/GroundTruthPass.cs, com.unity.perception/Runtime/GroundTruth/RenderPasses/HdrpPasses/InstanceSegmentationPass.cs, com.unity.perception/Runtime/GroundTruth/RenderPasses/HdrpPasses/LensDistortionPass.cs, com.unity.perception/Runtime/GroundTruth/RenderPasses/HdrpPasses/SemanticSegmentationPass.cs, com.unity.perception/Runtime/Unity.Perception.Runtime.asmdef
Fix a few HDRP warnings on 2020.1/2
**Editor Version Target (i.e. 19.3, 20.1)**: 2020.1/2020.2
**Tests Added**: None
**Core Scenario Tested**: Tested on 2020.1 and 2020.2
=> Fix HDRP warnings on 2020.X

com.unity.perception/Runtime/Randomization/Randomizers/RandomizerTag.cs
Just released I forgot to make RandomizerTag.OnEnable virtual (though I did make RandomizerTag.OnDisable virtual...).
=> RandomizerTag.OnEnable is now virtual

com.unity.perception/Runtime/GroundTruth/Labelers/BoundingBox3DLabeler.cs, com.unity.perception/Tests/Runtime/GroundTruthTests/BoundingBox3dTests.cs
Expanding tests for 3d bounding box to cover more cases. Discovered and fixed an issue where the transform hierarchy of the camera was not being applied properly.
**Tests Added**: Added a bunch of 3d bounding box tests.
**Core Scenario Tested**: Manually tested 3d bounding boxes on a bunch of combinations of transforms
=> Add 3dbb tests

com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/AnimationRandomizer.cs
AnimationRandomizer was causing warnings each frame when randomizing disabled GameObjects. This change fixes that warning by not randomizing disabled GameObjects.
**Tests Added**: None
**Core Scenario Tested**: Tested using random person placement scene on 2020.1
**At Risk Areas**: Animation randomization. Low risk fix
=> Fix warnings caused by animation randomizer

TestProjects/PerceptionHDRP/Assets/SemanticSegmentationLabelingConfiguration.asset, TestProjects/PerceptionHDRP/Packages/packages-lock.json, TestProjects/PerceptionURP/Assets/SemanticSegmentationLabelingConfiguration.asset, TestProjects/PerceptionURP/Packages/packages-lock.json, com.unity.perception/Editor/GroundTruth/IdLabelConfigEditor.cs, com.unity.perception/Editor/GroundTruth/LabelConfigEditor.cs, com.unity.perception/Editor/GroundTruth/SemanticSegmentationLabelConfigEditor.cs, com.unity.perception/Editor/GroundTruth/Uss/Styles.uss, com.unity.perception/Editor/GroundTruth/Uxml/ColoredLabelElementInLabelConfig.uxml, com.unity.perception/Editor/GroundTruth/Uxml/LabelConfig_Main.uxml, com.unity.perception/Runtime/GroundTruth/Labeling/SemanticSegmentationLabelConfig.cs, com.unity.perception/Runtime/GroundTruth/RenderPasses/CrossPipelinePasses/SemanticSegmentationCrossPipelinePass.cs, com.unity.perception/Tests/Runtime/GroundTruthTests/SegmentationGroundTruthTests.cs
This change adds a sky color to the semantic segmentation labeler.
Note that when this color is changed from the default black, it is no longer considered "background" by the visualizer. I think this is what users will expect, but open to feedback.
Before:
After:
**Tests Added**: Added tests for sky coloring
**Core Scenario Tested**: Tested on URP and HDRP
=> Adding sky color control to semantic segmentation

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Utilities/PoissonDiskSampling.cs
This PR addresses a problem Bowen found points sampled from the PoissonDiskSampling utility. Before this fix, the utility was generating a distribution of points that was biased toward the edges of the sampling region due to the over-fitting rejection-sampling edge-case behavior of the utility.
To fix this issue, the utility now samples a suitably larger point region and then crops it down to the original intended size to remove all points affected by this edge case behavior.
Finally, there was one final issue, and that was the initial point seeding. The first random point was being placed toward the center of the algorithm to compensate for making the occupancy grid too small (I generated the grid's dimensions with FloorToInt instead of CeilToInt lol). Now, the seed point is correctly …
=> Poisson disk super sampling

.yamato/environments.yml, com.unity.perception/Runtime/GroundTruth/Labelers/KeypointLabeler.cs, com.unity.perception/Tests/Runtime/GroundTruthTests/KeypointGroundTruthTests.cs
Keypoints were being mislabeled when visualizations were disabled due to the state of the keypoints being overwritten by frames happening in between simulation and readback.
This change makes a copy of the data before storing it for future use on readback.
**Tests Added**:  Added test for new case
**Core Scenario Tested**: Tested keypoints locally and on the PeopleSansPeople project
=> Fixing keypoint bugs when visualizations are disabled

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/GroundTruth/PerceptionCamera.cs, com.unity.perception/Runtime/GroundTruth/SimulationState.cs, com.unity.perception/Tests/Editor/DatasetCaptureEditorTests.cs
This change allows PerceptionCameras to function properly when using the 'step' button in the editor.
The labelers in the PerceptionCamera previously were not even running when using the 'step' button because the editor forces game time to increment at exactly 20ms per frame when using this button. This messed up the timing code in DatasetCapture.
This change detects the use of the step button and forces all sensors to start render and capture each frame. This will not work great with the 'frames between capture' feature, so open to feedback on that one.
**Tests Added**: Added editor test for dataset capture while stpping
**Core Scenario Tested**: Tested in editor
=> Supporting the 'step' button in the editor

com.unity.perception/CHANGELOG.md, com.unity.perception/Editor/Randomization/Editors/RunInUnitySimulationWindow.cs, com.unity.perception/Editor/Randomization/Editors/ScenarioBaseEditor.cs, com.unity.perception/Editor/Randomization/PropertyDrawers/UIntDrawer.cs, com.unity.perception/Editor/Randomization/PropertyDrawers/UIntDrawer.cs.meta, com.unity.perception/Editor/Randomization/Uxml/RunInUnitySimulationWindow.uxml, com.unity.perception/Editor/Randomization/VisualElements/Basic.meta, com.unity.perception/Editor/Randomization/VisualElements/Basic/UIntField.cs, com.unity.perception/Editor/Randomization/VisualElements/Basic/UIntField.cs.meta, com.unity.perception/Editor/Randomization/VisualElements/Basic/UxmlUIntAttributeDescription.cs, com.unity.perception/Editor/Randomization/VisualElements/Basic/UxmlUIntAttributeDescription.cs.meta
This PR adds a new UIntField UI element to enable users to configure the full range of random-seeds possible for their scenarios. Before this PR, the scenario's random seed constant (stored as an unsigned integer) was represented by an integer field that limited the potential seed values that could be assigned to the scenario and also introduced serialization issues when negative seed values were entered.
In addition, a randomize-seed button was also added to the Run in Unity Simulation window so users can quickly modify their scenario's random seed between runs.
No tests were added, though I will need to update the test rail to confirm the changes made in this PR.
=> added uint field element for random seeds

com.unity.perception/Editor/Randomization/PropertyDrawers/UIntDrawer.cs
One line fix to hide the surrogate integer field added to the UIntField
=> Changed uint surrogate field USS display attribute to none

com.unity.perception/Editor/Randomization/Editors/RunInUnitySimulationWindow.cs
A variable definition required for cloud rendering support was removed in a previous commit. I added it back.
=> Fixed a compile error when cloud rendering was selected

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/Randomization/Scenarios/Serialization/ScenarioSerializer.cs, com.unity.perception/Runtime/Randomization/Scenarios/Serialization/SerializationStructures.cs
The Datamaker service expects this key to be "stddev" instead of "standardDeviation". It looks like making the change here has fewer ramifications than on Datamaker. 
=> changed normal sampler standard deviation json key to "stddev"

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/Randomization/Parameters/CategoricalParameter.cs
Fixed an issue where categorical parameters sometimes tried to fetch items at i = categories.count, leading to an exception.
=> Categorical parameter fix

TestProjects/PerceptionURP/Assets/Tests/Editor/PerceptionCameraEditorUrpTests.cs, TestProjects/PerceptionURP/Packages/packages-lock.json, com.unity.perception/CHANGELOG.md, com.unity.perception/Editor/GroundTruth/IdLabelConfigEditor.cs, com.unity.perception/package.json
- Bug: When a new label was added to an empty id label config, the starting id (0 or 1) was ignored and the new label would always have an id of 0.
- Realized changelog was not updated after preview.4 release. Added a section for that release and modified the unreleased section accordingly.
=> Fixed an indexing issue with the Id Label Config editor

.yamato/upm-ci-testprojects.yml
Remove perception.editor from code coverage
=> Removing Editor from code coverage

com.unity.perception/CHANGELOG.md, com.unity.perception/Runtime/Randomization/Scenarios/ScenarioBase.cs, com.unity.perception/Tests/Runtime/Randomization/ScenarioTests/ExampleDelayRandomizer.cs, com.unity.perception/Tests/Runtime/Randomization/ScenarioTests/ExampleDelayRandomizer.cs.meta, com.unity.perception/Tests/Runtime/Randomization/ScenarioTests/ScenarioTests.cs
Ported over the DelayIteration feature from Residential Interiors along with a new test for it under `ScenarioTests`. 
**Tests Added**: `IterationCorrectlyDelays` along with `ExampleDelayRandomizer` which delays every n iteration starting from iteration n.
=> Ported over the ability to delay the current iteration
